name: CI

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  tr-nums:
    runs-on: ubuntu-latest
    name: unit tests

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          coverage run ./tr-nums -T
          coverage report --fail-under 100
          coverage html  # For artifact
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: htmlcov/
